services:
  - type: web
    name: test-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://ajadb_user:6USQiZSbW1rZAsYbFL1Fb7A12yzlPLG2@dpg-d32nhobipnbc73dbtk80-a.singapore-postgres.render.com/ajadb
      - key: DATABASE_URL_LOCAL
        value: postgresql://ajadb_user:6USQiZSbW1rZAsYbFL1Fb7A12yzlPLG2@dpg-d32nhobipnbc73dbtk80-a.singapore-postgres.render.com/ajadb
    plan: free